### ISSUE TITLE
select 组件使用疑问

### ISSUE THREAD

**Issue by hill1314** [ctyun/Mimiron2#4]
您好，我在使用 Select 组件时遇到一个问题，我在select 组件的 onChange 方法中使用了this.setState 方法设置了相关值，结果在下拉框显示时出现了问题，当我第一次点击下拉框时，下拉框显示成了空！
这是我的实例代码：
<Select labelName="调账级别:" name="selectType" data={this.state.selectType} defaultValue="1"
                            onSelect={this.selectChane}
                    />
selectChane(activeKey){
        this.setState({
            activeKey:activeKey,
            labelN: activeKey=='0'?'合同号': '用户邮箱',
        });
    },
不知道是我的使用不当，还是其他问题，麻烦在有空的时候帮我分析下，非常感谢！

**Comment by astwyg** [comment]
这是Query组件的bug, 估计要节后修了.

**Comment by astwyg** [comment]
Query针对此问题做了一次升级, 请核实.
