### ISSUE TITLE
时间控件问题

### ISSUE THREAD

**Issue by wangjiainchinatelecom** [ctyun/Mimiron2#5]
时间控件选择日期后能够提供一个format的字符串,例如:
选择了2016年6月7日,我想获取选择的月份则传入"yyyyMM",然后能给我返回"201606"这样的字符串

**Comment by astwyg** [comment]
已拒绝.

由于DatePicker组件会和其他若干组件进行交互, 且在前端维护Date型时间比较合理, 故不考虑DatePicker组件onChange返回值由Date类型变更为String类型.

但是, Misc.date2str(d,"YYYY-MM")方法可以将Date类型转换为String.
